filebeat.inputs:
- type: log
  paths:
  - /var/log/nginx/sk.access.log
  fields:
    logzio_codec: plain
    # Your Logz.io account token. You can find your token at
    #  https://app.logz.io/#/dashboard/settings/manage-accounts
    token: JYzHRwMIPnIxwirZytswgqwTWaGHYYRY
    type: nginx_access
  fields_under_root: true
  encoding: utf-8
  ignore_older: 3h
- type: log
  paths:
  - /var/log/nginx/sk.error.log
  fields:
    logzio_codec: plain
    # Your Logz.io account token. You can find your token at
    #  https://app.logz.io/#/dashboard/settings/manage-accounts
    token: JYzHRwMIPnIxwirZytswgqwTWaGHYYRY
    type: nginx_error
  fields_under_root: true
  encoding: utf-8
  ignore_older: 3h
registry_file: /var/lib/filebeat/registry

output.logstash:
  hosts: ["listener.logz.io:5015"]
  ssl:
    certificate_authorities: ['/etc/pki/tls/certs/COMODORSADomainValidationSecureServerCA.crt']